package com.mrezequiel.su.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val md_mascot_light_primary = Color(0xFF8A4A00)
private val md_mascot_light_onPrimary = Color(0xFFFFFFFF)
private val md_mascot_light_primaryContainer = Color(0xFFFFDDB5)
private val md_mascot_light_onPrimaryContainer = Color(0xFF2A1700)
private val md_mascot_light_secondary = Color(0xFF6F5B40)
private val md_mascot_light_onSecondary = Color(0xFFFFFFFF)
private val md_mascot_light_secondaryContainer = Color(0xFFF9DEBB)
private val md_mascot_light_onSecondaryContainer = Color(0xFF241A04)
private val md_mascot_light_tertiary = Color(0xFF7A5900)
private val md_mascot_light_onTertiary = Color(0xFFFFFFFF)
private val md_mascot_light_tertiaryContainer = Color(0xFFFFDF9E)
private val md_mascot_light_onTertiaryContainer = Color(0xFF261A00)
private val md_mascot_light_error = Color(0xFFBA1A1A)
private val md_mascot_light_errorContainer = Color(0xFFFFDAD6)
private val md_mascot_light_onError = Color(0xFFFFFFFF)
private val md_mascot_light_onErrorContainer = Color(0xFF410002)
private val md_mascot_light_background = Color(0xFFFFF8F2)
private val md_mascot_light_onBackground = Color(0xFF201A12)
private val md_mascot_light_surface = Color(0xFFFFF8F2)
private val md_mascot_light_onSurface = Color(0xFF201A12)
private val md_mascot_light_surfaceVariant = Color(0xFFEFE0D4)
private val md_mascot_light_onSurfaceVariant = Color(0xFF4F4539)
private val md_mascot_light_outline = Color(0xFF817567)
private val md_mascot_light_inverseOnSurface = Color(0xFFFBEEE2)
private val md_mascot_light_inverseSurface = Color(0xFF362F27)
private val md_mascot_light_inversePrimary = Color(0xFFFFB86B)
private val md_mascot_light_shadow = Color(0xFF000000)
private val md_mascot_light_surfaceTint = Color(0xFF8A4A00)
private val md_mascot_light_outlineVariant = Color(0xFFD3C4B4)
private val md_mascot_light_scrim = Color(0xFF000000)

private val md_mascot_dark_primary = Color(0xFFFFB86B)
private val md_mascot_dark_onPrimary = Color(0xFF4A2600)
private val md_mascot_dark_primaryContainer = Color(0xFF6B3A00)
private val md_mascot_dark_onPrimaryContainer = Color(0xFFFFDDB5)
private val md_mascot_dark_secondary = Color(0xFFDCC3A1)
private val md_mascot_dark_onSecondary = Color(0xFF3E2F16)
private val md_mascot_dark_secondaryContainer = Color(0xFF56452D)
private val md_mascot_dark_onSecondaryContainer = Color(0xFFF9DEBB)
private val md_mascot_dark_tertiary = Color(0xFFE4B86A)
private val md_mascot_dark_onTertiary = Color(0xFF3F2E00)
private val md_mascot_dark_tertiaryContainer = Color(0xFF5A4300)
private val md_mascot_dark_onTertiaryContainer = Color(0xFFFFDF9E)
private val md_mascot_dark_error = Color(0xFFFFB4AB)
private val md_mascot_dark_errorContainer = Color(0xFF93000A)
private val md_mascot_dark_onError = Color(0xFF690005)
private val md_mascot_dark_onErrorContainer = Color(0xFFFFDAD6)
private val md_mascot_dark_background = Color(0xFF201A12)
private val md_mascot_dark_onBackground = Color(0xFFECE1D3)
private val md_mascot_dark_surface = Color(0xFF201A12)
private val md_mascot_dark_onSurface = Color(0xFFECE1D3)
private val md_mascot_dark_surfaceVariant = Color(0xFF4F4539)
private val md_mascot_dark_onSurfaceVariant = Color(0xFFD3C4B4)
private val md_mascot_dark_outline = Color(0xFF9C8F80)
private val md_mascot_dark_inverseOnSurface = Color(0xFF201A12)
private val md_mascot_dark_inverseSurface = Color(0xFFECE1D3)
private val md_mascot_dark_inversePrimary = Color(0xFF8A4A00)
private val md_mascot_dark_shadow = Color(0xFF000000)
private val md_mascot_dark_surfaceTint = Color(0xFFFFB86B)
private val md_mascot_dark_outlineVariant = Color(0xFF4F4539)
private val md_mascot_dark_scrim = Color(0xFF000000)

val LightMascotTheme = lightColorScheme(
    primary = md_mascot_light_primary,
    onPrimary = md_mascot_light_onPrimary,
    primaryContainer = md_mascot_light_primaryContainer,
    onPrimaryContainer = md_mascot_light_onPrimaryContainer,
    secondary = md_mascot_light_secondary,
    onSecondary = md_mascot_light_onSecondary,
    secondaryContainer = md_mascot_light_secondaryContainer,
    onSecondaryContainer = md_mascot_light_onSecondaryContainer,
    tertiary = md_mascot_light_tertiary,
    onTertiary = md_mascot_light_onTertiary,
    tertiaryContainer = md_mascot_light_tertiaryContainer,
    onTertiaryContainer = md_mascot_light_onTertiaryContainer,
    error = md_mascot_light_error,
    errorContainer = md_mascot_light_errorContainer,
    onError = md_mascot_light_onError,
    onErrorContainer = md_mascot_light_onErrorContainer,
    background = md_mascot_light_background,
    onBackground = md_mascot_light_onBackground,
    surface = md_mascot_light_surface,
    onSurface = md_mascot_light_onSurface,
    surfaceVariant = md_mascot_light_surfaceVariant,
    onSurfaceVariant = md_mascot_light_onSurfaceVariant,
    outline = md_mascot_light_outline,
    inverseOnSurface = md_mascot_light_inverseOnSurface,
    inverseSurface = md_mascot_light_inverseSurface,
    inversePrimary = md_mascot_light_inversePrimary,
    surfaceTint = md_mascot_light_surfaceTint,
    outlineVariant = md_mascot_light_outlineVariant,
    scrim = md_mascot_light_scrim,
)

val DarkMascotTheme = darkColorScheme(
    primary = md_mascot_dark_primary,
    onPrimary = md_mascot_dark_onPrimary,
    primaryContainer = md_mascot_dark_primaryContainer,
    onPrimaryContainer = md_mascot_dark_onPrimaryContainer,
    secondary = md_mascot_dark_secondary,
    onSecondary = md_mascot_dark_onSecondary,
    secondaryContainer = md_mascot_dark_secondaryContainer,
    onSecondaryContainer = md_mascot_dark_onSecondaryContainer,
    tertiary = md_mascot_dark_tertiary,
    onTertiary = md_mascot_dark_onTertiary,
    tertiaryContainer = md_mascot_dark_tertiaryContainer,
    onTertiaryContainer = md_mascot_dark_onTertiaryContainer,
    error = md_mascot_dark_error,
    errorContainer = md_mascot_dark_errorContainer,
    onError = md_mascot_dark_onError,
    onErrorContainer = md_mascot_dark_onErrorContainer,
    background = md_mascot_dark_background,
    onBackground = md_mascot_dark_onBackground,
    surface = md_mascot_dark_surface,
    onSurface = md_mascot_dark_onSurface,
    surfaceVariant = md_mascot_dark_surfaceVariant,
    onSurfaceVariant = md_mascot_dark_onSurfaceVariant,
    outline = md_mascot_dark_outline,
    inverseOnSurface = md_mascot_dark_inverseOnSurface,
    inverseSurface = md_mascot_dark_inverseSurface,
    inversePrimary = md_mascot_dark_inversePrimary,
    surfaceTint = md_mascot_dark_surfaceTint,
    outlineVariant = md_mascot_dark_outlineVariant,
    scrim = md_mascot_dark_scrim,
)